version: "3"

services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq-nest'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
            - ./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./.docker/rabbitmq/rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
      
      networks:
        - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge